width: 1920
height: 1080
k: 12
query: 0
tau: 0.95
t_max: 40
fovea_size: 96
sectors: 128
dprime_min: 0.1
card_size: 192
digit_size: 48
card_min_distance: 288
cards_on: true
color_similarity: 0.0
background_contrast: 0.3

